<?php

namespace ApiBundle\Repository;

use ApiBundle\Repository\AbstractRepository\AbstractGenericRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends AbstractGenericRepository {
    
}
